import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const OUT_FILE = "src/server/embedded-assets.ts";

const ASSETS: { urlPath: string; diskPath: string }[] = [
	{ urlPath: "/index.html", diskPath: "dist/index.html" },
	{ urlPath: "/web/main.js", diskPath: "dist/web/main.js" },
	{ urlPath: "/web/main.css", diskPath: "dist/web/main.css" },
];

export function generateEmbeddedAssets() {
	for (const asset of ASSETS) {
		if (!existsSync(asset.diskPath)) {
			console.error(`${asset.diskPath} not found. Run bun run build first.`);
			process.exit(1);
		}
	}

	const lines: string[] = [
		"// Auto-generated by scripts/generate-embedded-assets.ts",
		"// Do not edit manually. Run `bun run build` to regenerate.",
		"",
	];

	const assetEntries: string[] = [];
	for (const asset of ASSETS) {
		const importPath = `../../${asset.diskPath}`;
		const varName = `_${asset.urlPath.replace(/[/.-]/g, "_")}`;
		lines.push(`import ${varName} from "${importPath}" with { type: "file" };`);
		assetEntries.push(`  "${asset.urlPath}": ${varName}`);
	}

	lines.push("");
	lines.push("export const embeddedAssets: Record<string, string> = {");
	lines.push(assetEntries.join(",\n"));
	lines.push("};");
	lines.push("");

	const content = lines.join("\n");

	const outDir = join("src", "server");
	if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
	writeFileSync(OUT_FILE, content, "utf-8");
	console.log(`Generated ${OUT_FILE} with ${ASSETS.length} embedded assets`);
}

if (import.meta.main) {
	generateEmbeddedAssets();
}
